name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# Excluir PRs que no nos interesan (Ruido)
exclude-labels:
  - 'skip-changelog'
  - 'maintenance'
  - 'chore'

autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  # Vamos a detectar esos merges de Develop/Staging automáticamente
  - label: 'maintenance'
    branch:
      - 'develop'
      - 'staging'
    title:
      - '/^Develop$/'
      - '/^Staging$/'

  - label: 'refactor'
    branch:
      -  '/refactor\/.+/'

categories:
  - title: '🚀 Nuevas Funcionalidades'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '🐛 Corrección de Errores'
    labels:
      - 'bug'
      - 'fix'
  - title: '🔌 Integraciones' # Veo que tienes fireblocks/key vault
    labels:
      - 'integration'

  - title: '💻 Refactorización de Código'
    labels:
      - 'refactor'
  # Esta categoría atrapa todo lo que NO tenga etiqueta
  - title: '🔍 Otros Cambios'
    labels: []

version-resolver:
  major:
    labels: ['breaking']
  minor:
    labels: ['enhancement', 'feature', 'refactor']
  default: patch

template: |
  ## Resumen de Cambios
  $CHANGES
