name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

# 1. Autolabeler: Traduce tus Ramas (Pizarra) a Etiquetas
autolabeler:
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
      - '/locales\/.+/'   # Tu rama de "Locales"
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
  - label: 'hotfix'
    branch:
      - '/hot\/.+/'       # Tu rama "Hot"
      - '/hotfix\/.+/'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
  - label: 'breaking'
    branch:
      - '/breaking\/.+/'

# 2. Categor칤as: Ordena las notas en el Release final
categories:
  - title: '游 Nuevas Funcionalidades'
    labels:
      - 'enhancement'
      - 'feature'
  - title: '游냍 Correcci칩n de Errores'
    labels:
      - 'bug'
      - 'fix'
  - title: '游댠 Hotfixes Cr칤ticos'
    labels:
      - 'hotfix'
  - title: '丘멆잺 Breaking Changes'
    labels:
      - 'breaking'
  - title: '游닄 Documentaci칩n'
    labels:
      - 'documentation'

# 3. Versionado Autom치tico (SemVer)
version-resolver:
  major:
    labels: ['breaking', 'major']
  minor:
    labels: ['enhancement', 'feature']
  default: patch

template: |
  ## Resumen de Cambios
  $CHANGES
  
  ---
  *游 Release generado autom치ticamente*
